class Command:
    DOWNLOAD = 1
    UPLOAD = 2    
    UPLOAD_CONNECTION = 3
    RESPONSE_CONNECTION = 8
    RESPONSE_UPLOAD = 4
    DOWNLOAD_CONECTION = 5
    RESPONSE_DOWNLOAD_CONECTION = 6
    DOWNLOAD_START = 7